name: Final Project 1
on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
  workflow_dispatch:
env:
  MyPAss: 1234

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Cache Dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: deps-node-modules-${{ hashFiles('**/package-lock.json')}}
      - name: Install Dependencies
        run: npm ci
      - name: Test Code
        run: npm run test

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Get Code
        uses: actions/checkout@v4
      - name: Cache Dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: deps-node-modules-${{ hashFiles('**/package-lock.json')}}
      - name: Install Dependencies
        run: npm install
      - name: Build Code
        run: npm run build
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-files
          path: dist


  deploy:
     runs-on: ubuntu-latest
     needs: build
     steps:
        - name: Get Code
          uses:  actions/checkout@v4

        - name: get Build files
          uses: actions/download-artifact@v4
          with:
            name: dist-files
            path: ./dist

        - name: Output Contents
          run: ls

        - name: Deploy
          id: deploy
          uses: ./.github/actions
          env:
            AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_ACCESS_KEY}}
            AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
          with:
            bucket: dkcohort
            dist-folder: ./dist
            bucket-region: us-east-1

        - name: output URL
          run: echo "Live URL:${{steps.deploy.outputs.website-url}}"



